END_TURN_SIGNAL = 69695
TWENTY_SIDED_DICE = 20

SUCCESSFUL_MOVE_SIGNAL = 1
SUCCESSFUL_ATTACK_SIGNAL = 2
SUCCESSFUL_PLAYER_TURN_SIGNAL = 3

UNSUCCESSFUL_MOVE_SIGNAL = -1
INVALID_ATTACK_SIGNAL = -2
MISSED_ATTACK_SIGNAL = -3
